### ISSUE TITLE
Цветовая тема как в системе

### ISSUE THREAD

**Issue by shuryak** [ubahwin/citydrive-unofficial#6]
Хотелось бы видеть возможность автоматической установки цветовой темы (тёмной/светлой) в соответствии с системной

**Comment by ubahwin** [comment]
Скорее всего темная тема вовсе будет убрана, я так понял дизайн СитиДрайва вообще не предусматривает темную тему, и чем больше я добавляю картинки и рисую как у них, тем хуже выглядит это в темной теме.
